class Config:
    exclude_props = [
        'button-demo-output.children',
        'menu-demo-output.children',
        'steps-demo.current',
        'steps-demo-current.children',
        'date-picker-demo-output.children',
        'date-range-picker-demo-output.children',
        'select-demo-output.children',
        'slider-demo-output.children',
        'transfer-demo-output.children',
        'table-demo-output.children',
        'table-server-side-demo.data',
        'table-server-side-demo.pagination',
        'tree-demo-output.children',
        'upload-demo-output.children',
        'github-stars.children',
        'spin-basic-demo-output.children',
        'spin-delay-demo-output1.children',
        'spin-delay-demo-output2.children',
        'spin-include-demo-output1.children',
        'spin-include-demo-output2.children',
        'spin-exclude-demo-output1.children',
        'spin-exclude-demo-output2.children',
        'input-value-demo-output.children',
        'input-nSubmit-demo-output.children',
        'input-nClicksSearch-demo-output.children',
        'tabs-demo.children',
        'tabs-demo.activeKey',
        'getting-started-notification-demo.children',
        'notification-container-demo1.children',
        'notification-container-demo2.children',
        'notification-container-demo3.children',
        'notification-container-demo4.children',
        'message-container-demo1.children',
        'message-container-demo2.children',
        'sider-custom-trigger-demo.collapsed'
    ]

    caches_path = './caches'
